#!/usr/bin/env bash
#
# setup.sh - Build the setup container and produce a self-contained web app.
#
# Usage:
#   ./setup.sh [output-dir]
#
# Arguments:
#   output-dir          Host path to write the full web app into (default: ./web)
#
# Environment:
#   APK_CACHE           Host path used to cache the downloaded APK between runs
#                       (default: ./cache). Bind-mounted to /cache in the container.
#   INCLUDE_GERMAN_LANG Set to "true" to also download the German APK and produce
#                       web/data/strings_de.js alongside the English strings.js.
#
# The output directory will mirror the repo's web/ layout:
#   output-dir/
#     index.html
#     css/
#     js/
#     data/          <- generated by the container (strings, chapters, assets)
#
# Open output-dir/index.html in a browser to run the app.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

OUTPUT_DIR="${1:-$SCRIPT_DIR/web}"
mkdir -p "$OUTPUT_DIR/data"
OUTPUT_DIR="$(realpath "$OUTPUT_DIR")"

CACHE_DIR="${APK_CACHE:-$SCRIPT_DIR/cache}"
mkdir -p "$CACHE_DIR"
CACHE_DIR="$(realpath "$CACHE_DIR")"

echo "Output:    $OUTPUT_DIR"
echo "APK cache: $CACHE_DIR"
if [[ "${INCLUDE_GERMAN_LANG:-}" == "true" ]]; then
    echo "German:    strings_de.js will be generated (INCLUDE_GERMAN_LANG=true)"
fi
echo ""

echo "Building setup image..."
docker build -t oathsworn-setup -f "$SCRIPT_DIR/Dockerfile" "$SCRIPT_DIR"

echo ""
echo "Running setup..."

# On Windows Git Bash (MINGW), MSYS path translation mangles Docker volume
# mount arguments, silently breaking bind mounts. Detect this environment,
# convert host paths to Windows format, and disable path translation so the
# container-side paths are passed through unchanged.
# The :z SELinux relabeling flag is Linux-only and unsupported on Windows.
if [[ "$(uname -s)" == MINGW* ]] || [[ "$(uname -s)" == MSYS* ]]; then
    DATA_MOUNT="$(cygpath -m "$OUTPUT_DIR/data"):/repo/web/data"
    CACHE_MOUNT="$(cygpath -m "$CACHE_DIR"):/cache"
    export MSYS_NO_PATHCONV=1
else
    DATA_MOUNT="$OUTPUT_DIR/data:/repo/web/data:z"
    CACHE_MOUNT="$CACHE_DIR:/cache:z"
fi

docker run --rm \
    -e HOST_UID="$(id -u)" \
    -e HOST_GID="$(id -g)" \
    -e INCLUDE_GERMAN_LANG="${INCLUDE_GERMAN_LANG:-}" \
    -v "$DATA_MOUNT" \
    -v "$CACHE_MOUNT" \
    oathsworn-setup

echo ""
echo "============================================================"
echo "===                    Copying Files                     ==="
echo "============================================================"
# Copy static web assets into the output directory.
# Skipped when OUTPUT_DIR is already the repo's web/ directory.
WEB_SRC="$SCRIPT_DIR/web"
if [[ "$(realpath "$OUTPUT_DIR")" != "$(realpath "$WEB_SRC")" ]]; then
    echo ""
    echo "Copying static files to $OUTPUT_DIR..."
    cp "$WEB_SRC/index.html" "$OUTPUT_DIR/"
    cp -r "$WEB_SRC/css"     "$OUTPUT_DIR/"
    cp -r "$WEB_SRC/js"      "$OUTPUT_DIR/"
    cp "$SCRIPT_DIR/serve/serve.sh" "$OUTPUT_DIR/serve.sh"
    chmod +x "$OUTPUT_DIR/serve.sh"
fi

echo ""
echo "============================================================"
echo "===                    Setup complete                    ==="
echo "============================================================"
echo "Open directly:  $OUTPUT_DIR/index.html"
echo ""
echo "Or serve via Docker:"
echo "  cd $OUTPUT_DIR"
echo "  ./serve.sh                         # http://localhost:8080"
echo "  ./serve.sh --port 3000             # http://localhost:3000"
echo "  ./serve.sh --domain example.com    # https://example.com"
echo ""
